# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
  - pwd
  - julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("add HTTP")'
  - julia --color=yes -e 'using Bukdu'
  - cd test
  - julia --color=yes runtests.jl
  - cd

after_success:
  # push coverage results to Codecov
  - if [[ "$TRAVIS_OS_NAME" == osx ]]; then julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("dev Bukdu"); Pkg.REPLMode.pkgstr("test --coverage Bukdu")' ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx ]]; then julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("add Coverage#master"); using Coverage; Codecov.submit(Codecov.process_folder(normpath(Pkg.devdir(), "Bukdu", "src")))' ; fi
